Test 2
nilearn/nilearn pull request #2710
Opened 2021-02-22 22:34 UTC by achamma723

Changes proposed in this pull request:
- Adding a warning in the fit function when both the design matrices and confounds

2021-02-23 09:15 UTC, NicolasGensollen requested changes
Thanks for addressing this @achamma723 !
Could you add a test checking that the warning is given correctly when providing a design matrix and confounds?

2021-02-23 09:15 UTC, NicolasGensollen commented on nilearn/glm/first_level/first_level.py
> +        if design_matrices is not None and confounds is not None:
I would expect it to be given at the beginning of the function rather than at the end, but otherwise the warning looks good.

2021-02-23 09:15 UTC, NicolasGensollen commented
Linking #2704

2021-02-23 12:50 UTC, achamma723 commented
@NicolasGensollen Can you tell more about this error?

2021-02-23 13:59 UTC, NicolasGensollen requested changes
I think we can simplify the test a lot (see my comment below). 
I haven't checked the Azure error you're getting yet, but I think we can update the test before debugging.

2021-02-23 13:59 UTC, NicolasGensollen commented on nilearn/glm/tests/test_first_level.py
> +def test_warning_fit():
I think this is too complicated for a simple warning check. I would be in favor of just checking this in `test_fmri_inputs` for example by adding something like:

```python
with pytest.warns(UserWarning,
                  match="If the design matrices are given"):
        FirstLevelModel(mask_img=mask).fit(fi, 
                                           design_matrices=d,
                                           confounds=conf)
```
WDYT?

2021-02-23 14:46 UTC, achamma723 commented
@NicolasGensollen Everything is good now. Thanks for your remarks!

2021-02-23 16:11 UTC, tsalo requested changes
Things look great. I just have a couple of minor requests. Additionally, would you mind (1) simplifying the PR title and (2) linking directly to #2704 with a [closing keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) (e.g., "Closes ")?

2021-02-23 16:11 UTC, tsalo commented on nilearn/glm/first_level/first_level.py
> +            warn('If the design matrices are given, it takes precedence over events and confounds.')
```suggestion
            warn('If design matrices are given, they take precedence over events and confounds.')
```

I'd lean toward using simpler words though. Perhaps `"If design matrices are supplied, confounds and events will be ignored."`.

2021-02-23 16:11 UTC, tsalo commented on nilearn/glm/first_level/first_level.py
> +        if design_matrices is not None and confounds is not None:
```suggestion
        if design_matrices is not None and (confounds is not None or events is not None):
```
Based on the warning, it seems like both confounds and events should be checked here.

2021-02-23 17:55 UTC, tsalo approved these changes
The changes look good to me. Will need to wait for @NicolasGensollen to re-review before merging though.

2021-02-23 18:34 UTC, NicolasGensollen approved these changes
This looks good to me too! :tada: 
Thanks for working on this @achamma723 and thanks for the reviews @tsalo ! :+1:

2021-02-23 20:48 UTC, bthirion approved these changes
LGTM, thx.

2021-02-24 08:56 UTC, NicolasGensollen commented
Thanks everybody! Merging...

2021-02-24 08:56 UTC, merged