Detrending before low and high pass filtering for the confounders in clean function
nilearn/nilearn pull request #2732
Opened 2021-03-12 18:16 UTC by jrasero

Changes proposed in this pull request:

- Fixes the issue raised in #2730 
- In particular, it changes the order of detrending and low and high pass filtering in `clean` such that it is the same that takes place with the input signal, i.e, first detrend and then frequency filtering. Currently, confounders were first low or high-pass filtered and then detrended, if requested from the beginning.

2021-03-13 11:16 UTC, bthirion reviewed
This looks good. Thx !
You simply need to add a test checking that the new behavior is enforced. This would be driectly derived from the example in #2730

2021-03-15 13:41 UTC, NicolasGensollen reviewed
There is a test failure for `test_clean_confounds()` on MacOS actions. I think we should increase the threshold on this line:

https://github.com/nilearn/nilearn/blob/e8d5f5dddaede697da1eb821a240ece52172c43f/nilearn/tests/test_signal.py#L436

This would also be a good place to add a test derived from the examples in #2730

2021-03-15 14:39 UTC, jrasero commented
Thanks for the feedback @bthirion , @NicolasGensollen. Just to be sure, as for the test checking, is it then OK if I add a few lines to `test_clean_confounds` function where I assert the expected behaviour?

2021-03-15 14:59 UTC, NicolasGensollen commented
>is it then OK if I add a few lines to test_clean_confounds function where I assert the expected behaviour?

Absolutely. I think this test would make sense either there, or in 

https://github.com/nilearn/nilearn/blob/e8d5f5dddaede697da1eb821a240ece52172c43f/nilearn/tests/test_signal.py#L288

2021-05-02 20:45 UTC, bthirion reviewed
LGTM, thx.
Maybe simply add a whatsnew entry.

2021-05-03 07:32 UTC, NicolasGensollen requested changes
Thanks @jrasero !
This looks good to me except one test currently failing on macOS:

https://github.com/nilearn/nilearn/blob/e747be0b3c39e431a83b0665b6689a67ba63d47b/nilearn/tests/test_signal.py#L432-L437

 As this test is passing on other OS, I think we should try to increase the threshold a little bit.
Also, could you add a whatsnew entry (in the 0.7.2.dev bugfix section of `nilearn/doc/whats_new.rst`)?

2021-05-03 17:07 UTC, jrasero commented
Hi @bthirion and @NicolasGensollen ,

As requested, I've added an entry to the whatsnew document.

Let me know if there's anything else to be done regarding this PR.

2021-05-03 21:41 UTC, bthirion commented
There is still a numerical error. in test_confounds.py, you need to increase the bound to 1000 * eps instead of 200 * eps.
Best,

2021-05-03 22:38 UTC, jrasero commented
> There is still a numerical error. in test_confounds.py, you need to increase the bound to 1000 * eps instead of 200 * eps.
> Best,

I increased the bound as suggested.

 It's strange, because I didn't touch this part of the function. Was this error not being happening before?

2021-05-04 07:18 UTC, NicolasGensollen approved these changes
LGTM 
Thanks @jrasero :+1:

2021-05-04 21:22 UTC, bthirion approved these changes
LGTM, thx !

2021-05-05 07:27 UTC, merged