update: issue #2763
nilearn/nilearn pull request #2770
Opened 2021-04-24 20:31 UTC by jithenshriyan

Replaced rewritten functions in multiple files by importing the original function.

Closes #2763.

Changes proposed in this pull request:

- Import `basic_paradigm()` function from original file to applicable files 
- Delete rewritten functions in applicable files

2021-04-24 20:48 UTC, jithenshriyan commented
I see an error in my syntax. I'm going to fix it and submit another PR.

Sorry, I'm a new contributor.

2021-04-26 07:48 UTC, NicolasGensollen requested changes
Thanks for working on this @jithenshriyan ! :+1: 
I enabled the CI to run on your PR, and tests are failing because of a typo (see one of my comments below).
One thing you can do to spot these issues before pushing is to run the tests locally. To run all tests, just run at the root of your local nilearn fork:

```
$ pytest -v --pyargs nilearn
```

To run a specific test file (for example `test_masking.py` here):

```
$ pytest -v nilearn/tests/test_masking.py
```

2021-04-26 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_dmtx.py
> +    assert_almost_equal, assert_array_equal, sassert_array_almost_equal,
typo here

2021-04-26 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_dmtx.py
> +    # basic test based on basic_paradigm() and glover hrf
Could you undo these parentheses additions?

2021-04-26 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_first_level.py
> +        # basic test based on basic_paradigm() and glover hrf
Same comment for this file

2021-04-26 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_paradigm.py
> +# from nilearn.glm.first_level import check_events
If the import is not needed anymore, it is better to just remove it

2021-04-26 18:10 UTC, jithenshriyan commented
Thanks! Definitely, a helpful tip as I am a new contributor. Will get to work on this today.

2021-04-27 07:48 UTC, NicolasGensollen requested changes
Thanks for addressing my reviews @jithenshriyan !
I left a few small comments below.
For now you are getting a lot of test failures since the function `basic_paradigm` that you are importing does not return a dataframe with a duration column.

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_paradigm.py
> +# import pytest
please remove the line if the import is not needed

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_dmtx.py
> +    # basic test based on basic_paradigm() and FIR
Could you undo these parentheses additions?

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_dmtx.py
> +    # basic test based on basic_paradigm(), plus user supplied regressors
same

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_first_level.py
> +        # basic test based on basic_paradigm() and glover hrf
same

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_paradigm.py
please remove the blank line here

2021-04-27 07:48 UTC, NicolasGensollen commented on nilearn/glm/tests/test_first_level.py
please remove this blank line

2021-04-28 17:03 UTC, jithenshriyan commented
Hi @NicolasGensollen, is there anything else you would like me to change or add before closing the PR? Thanks!

2021-04-28 17:38 UTC, NicolasGensollen commented
Hi @jithenshriyan 
There are still a lot of tests failing. I think most of them are failing because the column duration is missing from the dataframe you return.

2021-04-28 18:54 UTC, jithenshriyan commented
Interesting. I hadn't written the function myself, was merely just moving it. 

I'd be happy to fix it though!

```python3
def basic_paradigm():
    conditions = ['c0', 'c0', 'c0', 'c1', 'c1', 'c1', 'c2', 'c2', 'c2']
    onsets = [30, 70, 100, 10, 30, 90, 30, 40, 60]
    events = pd.DataFrame({'trial_type': conditions,
                           'onset': onsets})
    return events
```
It seems in the `basic_paradigm()` function we haven't defined a column named duration. It's written to return just conditions and onsets. 

Do you think making these changes would be sufficient?

```python3
def basic_paradigm():
    duration = np.full(20, 0.5)
    conditions = ['c0', 'c0', 'c0', 'c1', 'c1', 'c1', 'c2', 'c2', 'c2']
    onsets = [30, 70, 100, 10, 30, 90, 30, 40, 60]
    events = pd.DataFrame({'trial_type': conditions,
                           'onset': onsets, 'duration': duration})
    return events
```

2021-04-29 07:49 UTC, NicolasGensollen commented
>Interesting. I hadn't written the function myself, was merely just moving it.

Yes, these functions were very similar but not exactly the same since the duration column was missing in the one from `data_gen`, probably because this column wasn't used or because the function itself was never used. In any case, having only one of these functions will be better.

>Do you think making these changes would be sufficient?

The code you propose won't work because the duration array will be of length 20 instead of 9, which will fail at dataframe creation. 
I would suggest using the code from one of the deleted functions where `duration = 1 * np.ones(9)`.

2021-05-06 08:41 UTC, NicolasGensollen commented
Anything I can do to help @jithenshriyan ? 
I don't think there is much missing here.

2021-05-07 17:15 UTC, jithenshriyan commented
Sorry @NicolasGensollen, been a busy week. I'll get to work on it sometime this evening or over the weekend.

Appreciate your help. Thanks!

2021-05-07 17:34 UTC, NicolasGensollen commented
@jithenshriyan no worries, there is no rush. 
I was just checking if you were having some issues and if I could be of any help.

2021-05-14 18:39 UTC, jithenshriyan commented
Would this be fine then? 

```python
def basic_paradigm(): 
     conditions = ['c0', 'c0', 'c0', 'c1', 'c1', 'c1', 'c2', 'c2', 'c2'] 
     onsets = [30, 70, 100, 10, 30, 90, 30, 40, 60] 
     durations = 1 * np.ones(9) 
     events = pd.DataFrame({'trial_type': conditions, 
                            'onset': onsets, 
                            'duration': durations}) 
     return events 
```

2021-05-14 18:40 UTC, jithenshriyan commented
I got it from the original ```basic_paradigm()``` in ```test_first_level.py``` where ```duration = 1 * np.ones(9)```

2021-05-14 20:22 UTC, bthirion commented
> Would this be fine then?

LGTM, thx !

2021-05-28 07:25 UTC, NicolasGensollen requested changes
Thanks @jithenshriyan !
You are getting some errors because you removed an import in one of the test file.
Could you also merge/rebase master?

2021-05-28 07:25 UTC, NicolasGensollen commented on nilearn/glm/tests/test_paradigm.py
> -from nilearn.glm.first_level import check_events
You need to keep this import

2022-05-11 16:25 UTC, ymzayek commented
> Thx @jithenshriyan ! @ymzayek is it OK to rebase it on main ? Best,

Yes I will give it a go

2022-05-30 07:35 UTC, closed without merging