[DOC] add Parameter estimate/beta to glossary
nilearn/nilearn pull request #2914
Opened 2021-08-05 15:29 UTC by mekman

Adding Parameter estimate/beta to glossary. No functional changes.

See #2913

2021-08-06 06:31 UTC, NicolasGensollen requested changes
Thanks for opening this @mekman !
I left a few suggestions below. 
Note that if you want to reference a term in the glossary you need to use 
```
:term:`word_in_glossary`
```

2021-08-06 06:31 UTC, NicolasGensollen commented on doc/glossary.rst
> +        `Parameter estimate`_.
```suggestion
        See :term:`Parameter estimate`.
```

2021-08-06 06:31 UTC, NicolasGensollen commented on doc/glossary.rst
> +        In the context of a `GLM`_, each `contrast`_ comparing rows in the
```suggestion
        In the context of a :term:`GLM`, each :term:`contrast` comparing rows in the 
```

2021-08-06 06:31 UTC, NicolasGensollen commented on doc/glossary.rst
> +        well the underlying model fits the data at each voxel. For statistical
```suggestion
        well the underlying model fits the data at each :term:`voxel`. For statistical 
```

2021-08-06 06:31 UTC, NicolasGensollen commented on doc/glossary.rst
> +        `beta`_, is commonly converted to either a t-, or z-statistic. In
```suggestion
        :term:`beta`, is commonly converted to either a t-, or z-statistic. In 
```

2021-08-06 06:38 UTC, mekman commented
Thank you @NicolasGensollen for pointing that out. Fixed now.

2021-08-06 14:57 UTC, tsalo commented
Can you perhaps link to the glossary in the `compute_contrast` docstring and/or in examples as well?

2021-08-09 17:15 UTC, mekman commented
Just a quick note, I will continue working on this by the end of August. Thanks for the feedback so far.

2021-09-28 07:30 UTC, NicolasGensollen commented
Hi @mekman 
I think this was almost ready to be merged and only missing a few references to the new entry in the glossary as @tsalo suggested.
Let me know if I can help.

2022-07-27 15:27 UTC, tsalo commented
@mekman are you able to finish this up? If not, would you mind if I made the final changes to get it ready to merge?

2022-08-08 17:16 UTC, tsalo commented
I've made the necessary changes in #3330, so I will close this now.

2022-08-08 17:16 UTC, closed without merging