[DOC] Note that Masker.inverse_transform only performs spatial unmasking in docstring
nilearn/nilearn pull request #3445
Opened 2022-12-06 16:43 UTC by RobWilliamson15

Closes #3416 .

Changes proposed in this pull request:

- Adds a note to inverse transform section, stating that it only performs spatial unmasking

2022-12-06 21:52 UTC, tsalo requested changes
Can you add this information to the maskers' `inverse_transform` method's docstrings and go into more detail about what it means to only perform spatial unmasking?

2022-12-07 22:00 UTC, bthirion commented on doc/manipulating_images/masker_objects.rst
> +  The data is only brought back into either a 3D or 4D represnetaion.
```suggestion
  The data is only brought back into either a 3D or 4D representation.
```

2023-01-12 20:55 UTC, tsalo requested changes
I made a few suggestions to add more detail about what it means to only perform spatial unmasking.

2023-01-12 20:55 UTC, tsalo commented on doc/manipulating_images/masker_objects.rst
> +  The data is only brought back into either a 3D or 4D represenetation.
```suggestion
  The data is only brought back into either a 3D or 4D representation,
  without inverting any signal processing performed by `transform`.
```

2023-01-12 20:55 UTC, tsalo commented on nilearn/maskers/base_masker.py
> +
```suggestion
        This step only performs spatial unmasking,
        without inverting any additional processing performed by ``transform``,
        such as temporal filtering or smoothing.

```

2023-01-18 13:28 UTC, ymzayek commented
Hi @RobWilliamson15 I think not much is left to do to finish this. Can you rebase on main, make the requested changes, and add a whatsnew entry? Then we can give it another round of reviews. Thx!

2023-01-26 12:06 UTC, ymzayek commented on doc/manipulating_images/masker_objects.rst
> +  without inverting any signal processing performed by 'transform'.
```suggestion
  without inverting any signal processing performed by ``transform``.
```

2023-01-26 12:07 UTC, ymzayek commented on doc/changes/latest.rst
> +- Addition to docs to note that Masker.inverse_transform only performs spatial unmasking (:gh: `3445` by `Robert Williamson`_).
```suggestion
- Addition to docs to note that :meth:`~maskers.BaseMasker.inverse_transform` only performs spatial unmasking (:gh:`3445` by `Robert Williamson`_).
```

2023-01-26 12:14 UTC, ymzayek commented
@RobWilliamson15 thanks! Just a couple of small things above. Also can you rebase on main and resolve the conflicts. There's been a release since this PR was opened and [`doc/changes/latest.rst`](https://github.com/nilearn/nilearn/blob/main/doc/changes/latest.rst) has changed

2023-01-26 13:08 UTC, ymzayek reviewed
@RobWilliamson15 seems that something went wrong with resolving the merge conflicts. Your entry under Enhancements should be the only one in `latest.rst`. See the document on main https://github.com/nilearn/nilearn/blob/main/doc/changes/latest.rst

2023-01-26 13:08 UTC, ymzayek commented on doc/changes/latest.rst
> +- Addition to docs to note that :meth:`~maskers.BaseMasker.inverse_transform` only performs spatial unmasking (:gh: `3445` by `Robert Williamson`_).
The space after :gh: needs to be removed for the link to work

```suggestion
- Addition to docs to note that :meth:`~maskers.BaseMasker.inverse_transform` only performs spatial unmasking (:gh:`3445` by `Robert Williamson`_).
```

2023-01-26 15:30 UTC, ymzayek approved these changes
Thx @RobWilliamson15 LGTM! The failure of the test timing out on Azure Pipelines doesn't seem related to this PR

2023-01-26 20:27 UTC, bthirion approved these changes
LGTM, thx.

2023-01-27 09:35 UTC, merged