refactor test with error raising
nilearn/nilearn pull request #3854
Opened 2023-07-19 21:11 UTC by FrancoisPgm

Closes #3796 .

Changes proposed in this pull request:

- the tests in the form `pytest.raises(<Error>, <func>, <args>)` were changed to use the `with pytest.raises(<Error>)` context manager

2023-07-20 02:04 UTC, Remi-Gau commented on nilearn/surface/tests/test_surface.py
Seems that black was run on this file and 2 others when it should not have.

It is something a bit tricky about our current black set up at the moment that can leas this kind of outcome.

We can try to look how to fix that tomorrow.

2023-07-20 02:07 UTC, Remi-Gau requested changes
Changes look good (except for black going to town when it should not have) but you should:

-     add an entry to the changelog
-     add yourself to the list of contributors

see here: https://nilearn.github.io/dev/development.html#changelog

and ask us if you need guidance

2023-07-20 16:03 UTC, Remi-Gau commented
> The failed flake8 test comes from a not yet blacked file, so not my fault :P

Can you try to fix the issues manually to make flake8 happy.

2023-07-20 17:24 UTC, ymzayek reviewed
Looks good! Just minor flake8 issues: https://github.com/nilearn/nilearn/actions/runs/5613902463/job/15210922744?pr=3854

2023-07-20 21:43 UTC, Remi-Gau commented
That list of commit messages is going in the wrap up session!!!

I feel you so much on this.

2023-07-21 13:11 UTC, ymzayek approved these changes
Thx @FrancoisPgm! Flake8 is happy and so are we!

2023-07-21 13:27 UTC, Remi-Gau approved these changes
LGTM. Thanks for doing this @FrancoisPgm

2023-07-21 13:27 UTC, Remi-Gau commented
Let me know if you want us to handle the merge conflict: it should be easy to fix but, ping us if you need help

2023-07-21 13:33 UTC, Remi-Gau commented
Will fix it

2023-07-21 13:33 UTC, merged