replace skipped doctests with default code-blocks
nilearn/nilearn pull request #3858
Opened 2023-07-20 15:18 UTC by psadil

Closes #3681.

Changes proposed in this pull request:

- doctest blocks that had skipped lines were converted to (default) code-blocks
- output that could have been tested against via a doctest ([e.g.](https://github.com/psadil/nilearn/blob/6fb7df5c7af3ec9bcc447e2b3ee274df7273e370/doc/manipulating_images/input_output.rst?plain=1#L121-L127)) were converted into comments

2023-07-20 17:30 UTC, Remi-Gau commented on doc/building_blocks/neurovault.rst
> +    ... max_images=100)
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:39 UTC, Remi-Gau requested changes
I think we should remove the ellipsis (`...`) in the code blocks.

Do you mind fixing this?

2023-07-20 17:39 UTC, Remi-Gau commented on doc/building_blocks/neurovault.rst
> +    ... max_images=7)
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:39 UTC, Remi-Gau commented on doc/building_blocks/neurovault.rst
> +    ... max_images=7)
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:39 UTC, Remi-Gau commented on doc/building_blocks/neurovault.rst
> +    ... image_terms={}, max_images=7)
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:39 UTC, Remi-Gau commented on doc/building_blocks/neurovault.rst
> +  ...                                      max_images=7)
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:39 UTC, Remi-Gau commented on doc/plotting/index.rst
> +     ...                                     title="Motor contrast")
I don't think we need to keep the ellipsis in those code blocks

2023-07-20 17:46 UTC, psadil commented
> I think we should remove the ellipsis (`...`) in the code blocks.
> 
> Do you mind fixing this?

Will do!

2023-07-20 19:20 UTC, Remi-Gau commented
@psadil Do you want to  update the changelog and add yourself to the list of contributors?

https://nilearn.github.io/dev/development.html#changelog

2023-07-20 19:53 UTC, psadil commented
> @psadil Do you want to update the changelog and add yourself to the list of contributors?
> 
> https://nilearn.github.io/dev/development.html#changelog

Sure thing. In this pull request or another?

2023-07-20 19:55 UTC, Remi-Gau commented
> Sure thing. In this pull request or another?

do it directly here: helps keep track of what changelog entry corresponds to what PR

2023-07-21 10:11 UTC, Remi-Gau approved these changes
Looks good to me.

2023-07-21 13:18 UTC, ymzayek approved these changes
Thx @psadil !

2023-07-21 13:18 UTC, merged