change creation of region_names and add test
nilearn/nilearn pull request #4360
Opened 2024-04-05 18:39 UTC by mtorabi59

- Closes #4359 

Changes proposed in this pull request:

- change how `region_names_` attribute of `NiftiLabelsMasker` is defined
- add tests to check the correctness of the correspondence between region names and region ids after fit_transform, e.g. resampling and masking.

2024-04-05 18:53 UTC, mtorabi59 commented
I am not sure if I should keep definition of `self.region_id_name` in `__init__` or move it to `fit` after definition of `self.labels_img_`

2024-04-07 20:29 UTC, bthirion reviewed
LGTM otherwise.

2024-04-07 20:29 UTC, bthirion commented on nilearn/maskers/tests/test_nifti_labels_masker.py
> +    Check that the same region names and ids correspond to eac other
```suggestion
    Check that the same region names and ids correspond to each other
```

2024-04-08 08:34 UTC, Remi-Gau commented
This seems top break the report builder script in the doc build:

```
Traceback (most recent call last):
  File "/home/runner/work/nilearn/nilearn/doc/visual_testing/reporter_visual_inspection_suite.py", line 438, in <module>
    report_nifti_labels_masker()
  File "/home/runner/work/nilearn/nilearn/doc/visual_testing/reporter_visual_inspection_suite.py", line 313, in report_nifti_labels_masker
    masker = NiftiLabelsMasker(
             ^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/nilearn/maskers/nifti_labels_masker.py", line 212, in __init__
    _utils.niimg.safe_get_data(labels_img)
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/nilearn/_utils/niimg.py", line 58, in safe_get_data
    data = _get_data(img)
           ^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/site-packages/nilearn/_utils/niimg.py", line 23, in _get_data
    if img._data_cache is not None:
       ^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_data_cache'
```

Can you try to run `doc/visual_testing/reporter_visual_inspection_suite.py` to see what's going on?

2024-04-23 17:12 UTC, mtorabi59 commented
Do I need to do anything regarding this PR? I think all the issues are addressed.

2024-04-25 10:57 UTC, Remi-Gau requested changes
Since this is a new public attribute, do you think you could update the doc string to explain what it is?

2024-04-25 14:51 UTC, mtorabi59 commented
> Since this is a new public attribute, do you think you could update the doc string to explain what it is?

I'm not sure if we want `region_id_name_` to be a public attribute, do we? My goal was to create so we can use it to create `region_names_`

2024-04-25 14:53 UTC, mtorabi59 commented
@Remi-Gau but I think it's a good idea to add some comments to explain to the developers what this attribute is

2024-04-25 14:56 UTC, Remi-Gau commented
> > Since this is a new public attribute, do you think you could update the doc string to explain what it is?
> 
> I'm not sure if we want `region_id_name_` to be a public attribute, do we? My goal was to create so we can use it to create `region_names_`

OK in this case rename it to `_region_id_name` to signify this a "private" attribute.

2024-04-25 21:00 UTC, bthirion reviewed
Still LGTM. Probably deserves a whatsnew entry.

2024-04-26 06:16 UTC, bthirion approved these changes
Thx.

2024-06-28 12:45 UTC, Remi-Gau commented on nilearn/maskers/tests/test_nifti_labels_masker.py
> +    _ = masker.fit().transform(fmri_img)
```suggestion
    masker.fit().transform(fmri_img)
```

2024-06-28 12:49 UTC, Remi-Gau commented on nilearn/maskers/nifti_labels_masker.py
> +        self._region_id_name = None
```suggestion
        self._region_id_name = {}
```
this way we know this is always a dict

2024-06-28 15:11 UTC, Remi-Gau approved these changes

2024-06-28 15:14 UTC, merged

2024-06-28 15:14 UTC, Remi-Gau commented
Sorry it took me so long to get back to this one @mtorabi59