add width input to view_img()
nilearn/nilearn pull request #4416
Opened 2024-05-17 14:16 UTC by alexsayal

- Closes #4415 

Changes proposed in this pull request:

- Add input field for the output image width of view_img() in pixels

2024-05-17 21:42 UTC, bthirion reviewed
The change LGTM. I don't understand the codecov issue.

2024-05-17 21:42 UTC, bthirion commented on nilearn/plotting/html_stat_map.py
> +    # width_view = 600
Please remove the line

2024-05-20 21:44 UTC, bthirion approved these changes
LGTM, thx.

2024-05-21 09:33 UTC, man-shu commented
> The change LGTM. I don't understand the codecov issue.

The coverage just updates slowly, I think. Now it is 100%, so all good!

2024-05-21 09:38 UTC, man-shu requested changes
Thanks for the contribution @alexsayal ! The change looks good to me too!

Since this is your first contribution could you please:

1.  add yourself to the authors section of `CITATION.cff`
2. also add this change to the `nilearn/doc/changes/latest.rst`

See https://nilearn.github.io/stable/development.html#changelog for more details, and feel free to ping me here if needed!

2024-05-21 13:36 UTC, man-shu commented
Just made a couple of changes:
- the docs builder was failing because `view_img` can be directly imported from `nilearn.plotting` (no need to reference `html_stat_map`)
- this is probably better suited as an Enhancement in the API

2024-05-21 18:16 UTC, man-shu approved these changes
All good now. Thanks!

2024-05-21 18:17 UTC, merged