[DOC] Explaining how Decoder works
nilearn/nilearn pull request #4437
Opened 2024-06-06 09:32 UTC by man-shu

- Closes #4344 

Changes proposed in this pull request:

- A new example replicating each step performed inside the Decoder object using sklearn

2024-06-06 09:36 UTC, man-shu commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +plt.show()
To explain how the One-vs-Other label encoding works
![binary_classes](https://github.com/nilearn/nilearn/assets/35485429/1b29d0c6-0149-47e2-ab31-9045ee0732de)

2024-06-06 09:38 UTC, man-shu commented
Started drafting the example and thought to get some general feedback on the structure.
@bthirion, please LMK if this looks ok.
Thanks!

2024-06-06 21:08 UTC, bthirion reviewed
Looks good so far.

2024-06-06 21:08 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# of trials, each corresponding to one of the 8 labels we selected above.
864 is only the number of time points in the fMRI data after concatenation and removal of rest time intervals. Strictly speaking this is not the number of events

2024-06-07 16:14 UTC, man-shu commented
In [this comment](https://github.com/nilearn/nilearn/pull/4438#pullrequestreview-2103186479) @bthirion said:

> Thx !
I only have one hesitation: when we use a XXXcv estimator, what cross-validation scheme is used ? The problem is that with neuroimaging, naive cross-validation schemes may lead to bad estimates. The well-known example id LOO, which is broken by the serial dependence in the data.

2024-06-07 16:19 UTC, man-shu commented
We use the default cv scheme for all ...CV estimators in sklearn. Turns out they are different for different estimators:
- for LogisticRegressionCV it is StratifiedKFold with K=5: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegressionCV.html
- for RidgeClassifierCV and RidgeCV it is Leave-One-Out: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.RidgeClassifierCV.html
- for LassoCV it is KFold with K=5: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html

2024-06-07 20:48 UTC, bthirion commented
OK. I guess that in any case, users are supposed to do the job manually if they want a specific cross val scheme.

2024-06-10 10:46 UTC, man-shu commented
> OK. I guess that in any case, users are supposed to do the job manually if they want a specific cross val scheme.

But there's no easy way to select the internal cross-validation scheme for the hyperparameter optimization. The cv parameter in the Decoder object specifies the cross-validation scheme for the final train-test split.

I suppose one could select the internal cross-validation via the estimator parameter in the Decoder object. But users are not even aware that such internal cross-validation exists, so why would they select it.

2024-06-10 20:21 UTC, bthirion commented
I think you're right. We also have experts users who want to control details, but precisely, they can make all the necessary steps manually.
Best,

2024-07-05 12:38 UTC, man-shu commented
Just noticed that the Decoder does not do ReNA clustering. 
Instead, more specialized FREM classifier and regressor do this. See #4488

2024-07-05 17:44 UTC, man-shu commented
> I think you're right. We also have experts users who want to control details, but precisely, they can make all the necessary steps manually. Best,

Do you think we should do something about this? For example, either letting people select the internal cross-validation scheme and/or picking the best practice?

2024-07-08 16:54 UTC, man-shu commented
This is ready for a review @bthirion! Please let me know if you have any comments?

2024-07-08 19:53 UTC, bthirion reviewed
LGTM overall.
Deserves a whatsnew entry

2024-07-08 19:53 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +Sklearn pipeline.
Scikit-Learn

2024-07-08 19:53 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +cmap = ListedColormap(["white"] + list(plt.cm.tab10.colors)[0:8])
```suggestion
cmap = ListedColormap(["white"] + list(plt.cm.tab10.colors)[0:n_conditions])
``` where n_conditions has been set previously

2024-07-09 20:46 UTC, bthirion reviewed
Still minor details, but close to merge.

2024-07-09 20:46 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# of selected trials, each corresponding to one of the 8 labels we selected
More exactly,  it corresponds to the number of brain volumes acquired while visual stimuli were presented.

2024-07-09 20:46 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +screen_percent = adjust_screening_percentile(20, mask_vt_loaded)
Maybe print the value ?

2024-07-09 20:46 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# each voxel and to only keep the ones that have highest 20 percentile scores,
But IIRC thsi si 20 percent of the MNI brain volume, right ?

2024-10-04 11:32 UTC, Remi-Gau requested changes

2024-10-04 11:32 UTC, Remi-Gau commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# These 20 percentile voxels are w.r.t. the volume of the standard MNI152 brain
```suggestion
# These 20 percentile voxels are with restpect to the volume of the standard MNI152 brain
```

2024-10-04 11:32 UTC, Remi-Gau commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# results in a structured way that can be easily accessed and analysed.
maybe link to this new example from this file: examples/00_tutorials/plot_decoding_tutorial.py

This way when people are done with the basic intro they can look deeper with this new example.

2024-10-04 12:02 UTC, bthirion reviewed
LGTM otherwise

2024-10-04 12:28 UTC, bthirion reviewed
Minor details.

2024-10-04 12:28 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# These 20 percentile voxels are with restpect to the volume of the standard
```suggestion
# These 20 percentile voxels are with respect to the volume of the standard
```

2024-10-04 12:28 UTC, bthirion commented on examples/02_decoding/plot_haxby_understand_decoder.py
> +# voxels than the selected percentile, then all voxels in the mask are used.
```suggestion
# voxels than the selected percentile, all voxels in the mask are used.
```

2024-10-04 13:00 UTC, bthirion approved these changes
LGTM, thx.

2024-10-04 13:10 UTC, Remi-Gau approved these changes
Good with me.
Let's merge when CI finishes.

2024-10-04 14:59 UTC, merged