[FIX] Make load_confounds return None for confounds if no cleaning strategy is provided
nilearn/nilearn pull request #4636
Opened 2024-10-13 21:45 UTC by mibur1

- Closes #4570 

**Changes proposed in this pull request:**

If the user passes an empty cleaning strategy to `nilearn.interfaces.fmriprep.load_confounds`
- Display warning 
- Return `None` for confounds

Adding the check at the end of the function is the simplest solution (imo) as the workflow still needs to run for `sample_mask_out`. I'm not sure if a test is necessary, please let me know if I should provide one.

2024-10-14 09:01 UTC, Remi-Gau requested changes
small changes to do

2024-10-14 09:01 UTC, Remi-Gau commented
> a test is necessary, please let me know if I should provide one.

Yeah better had a test for this to avoid any regression of the behavior in the future.

2024-10-23 07:59 UTC, Remi-Gau approved these changes

2024-10-23 07:59 UTC, Remi-Gau commented
Let's wait for CI to run but this should be good to go.

2024-10-23 13:06 UTC, bthirion approved these changes
LGTM, thx.

2024-10-23 13:06 UTC, bthirion commented on nilearn/interfaces/fmriprep/load_confounds.py
> +        confounds_out = None
OK, this was discussed in #4570

2024-10-23 14:10 UTC, merged