Fix RUF012: Resolve mutable class default issue[STY] Fix RUF012: Mutable class defaults
nilearn/nilearn pull request #4954
Opened 2024-12-15 16:45 UTC by badrinini

his Pull Request fixes all occurrences of the RUF012 error related to the use of mutable default values in Python classes. The RUF012 error occurs when a mutable object (such as a list or dictionary) is used as a default value for a class argument, which can lead to unexpected behavior due to the mutability of these objects.

Changes made:
Replaced mutable default values (e.g., lists, dictionaries) with immutable defaults (e.g., None or immutable objects like tuples).
Updated the code to ensure that default values are safe and do not cause unintended behavior when modified by multiple class instances.
Why these changes?
Using mutable default values in method or class constructors can lead to hard-to-detect bugs. By using immutable default values (such as None), we avoid these issues and adhere to best practices recommended by the ruff tool.

Related Links
[RUF012 - mutable-class-default](https://docs.astral.sh/ruff/rules/#mutable-class-default)

2024-12-16 09:58 UTC, Remi-Gau commented on nilearn/regions/parcellations.py
> +        pass
```suggestion
```

I don't think this is needed

2024-12-16 10:06 UTC, Remi-Gau requested changes
Can you delete this line from the pyproject.toml to make sure this PR fixes all instances of this error?
https://github.com/nilearn/nilearn/blob/5d287b127aab0247c682c744739a9b67a3d2ed85/pyproject.toml#L167

2024-12-16 10:08 UTC, Remi-Gau commented on nilearn/decoding/space_net.py
> +from typing import ClassVar
You are getting some code style errors on the import.

See here: https://results.pre-commit.ci/run/github/1235740/1734281156.IFMbzslZRvWBfnsXqlJd_Q

My suggestion to fix them.

Install tox: `pip install tox`

From the root of the repository run:

```
tox
```

This should autofix most issues that you can them commit and push.

2024-12-16 17:09 UTC, Remi-Gau requested changes
You are missing a few more changes from tuple to list

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.2, 2.6)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.2, 2.6)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.2, 3.5)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.5)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.0, 7.6)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.0, 7.6)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.6, 2.3)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.6, 2.3)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.2, 3.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.0)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.2, 3.2)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.2)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (2.2, 3.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.0)
```

2024-12-16 17:09 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[tuple[float, float]] = (4.0, 5.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = (4.0, 5.0)
```

2024-12-16 17:10 UTC, Remi-Gau requested changes
You also need to update the changelog and add yourself as a contributor in the CITATION.cff file in the root of the repo:

see here for more info
https://nilearn.github.io/stable/development.html#changelog

2024-12-16 18:00 UTC, badrinini commented
I hope you are doing well.

I wanted to inform you that I have addressed the error you pointed out and
have also implemented the recommendations you provided.

I would be grateful if you could take a moment to review the changes.
Should you have any further suggestions or if anything requires additional
adjustments, please feel free to let me know.

Thank you once again for your valuable guidance and assistance.

Best regards,
Traore Idrissa

Le lun. 16 déc. 2024 à 18:11, Remi Gau ***@***.***> a écrit :

> ***@***.**** requested changes on this pull request.
>
> You also need to update the changelog and add yourself as a contributor in
> the CITATION.cff file in the root of the repo:
>
> see here for more info
> https://nilearn.github.io/stable/development.html#changelog
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nilearn/nilearn/pull/4954#pullrequestreview-2506803847>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BIKTQ2G2CA65FSNZ4N27SYT2F4CTRAVCNFSM6AAAAABTUWQQZSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDKMBWHAYDGOBUG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-12-17 08:48 UTC, Remi-Gau commented on CITATION.cff
> +    family-names: TRAORE
```suggestion
    given-names: Idrissa
    family-names: Traore
```

2024-12-17 08:48 UTC, Remi-Gau commented on CITATION.cff
> +    family-names: TRAORE
let's only have the first letter in upper case

2024-12-17 08:49 UTC, Remi-Gau commented on doc/changes/latest.rst
> +:bdg-dark:Code Fix all occurrences of the RUF012 error related to mutable default values in Python classes (:gh:[PR_NUMBER] by TRAORE IDRISSA_).
```suggestion
:bdg-dark:Code Fix all occurrences of the RUF012 error related to mutable default values in Python classes (:gh:[4954] by Idrissa Traore_).
```

2024-12-17 08:54 UTC, Remi-Gau commented on CITATION.cff
> +    affiliation: IMT Atlantique, Brest, France
```suggestion
  - given-names: Idrissa
    family-names: Traore
    affiliation: IMT Atlantique, Brest, France
```

2024-12-17 09:00 UTC, Remi-Gau commented
@badrinini 
I fixed a couple of issues: some classes attributes were still typed as tuple and there were a few styling issues

2024-12-17 09:42 UTC, Remi-Gau approved these changes
Good with me

2024-12-17 10:18 UTC, Remi-Gau commented
oops tests are failing because we updated the type annotation but not the code: let me fix that

2024-12-17 10:18 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.6, 3.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.6, 3.0]
```

2024-12-17 10:19 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = (2.2, 3.0)
```suggestion
    _cut_displayed: ClassVar[str] = "y"
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.0]
```

2024-12-17 10:19 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = (2.2, 3.4)
```suggestion
_default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```

2024-12-17 10:19 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = (2.2, 3.4)
```suggestion
_default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```

2024-12-17 10:19 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = (2.6, 3.0)
```suggestion
_default_figsize: ClassVar[list[float, float]] = [2.6, 3.0]
```

2024-12-17 10:19 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = (2.6, 2.8)
```suggestion
_default_figsize: ClassVar[list[float, float]] = [2.6, 2.8]
```

2024-12-17 10:20 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.2, 2.6)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.2, 2.6]
```

2024-12-17 10:20 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.5)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.5]
```

2024-12-17 10:20 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.0, 7.6)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.0, 7.6]
```

2024-12-17 10:20 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.6, 2.3)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.6, 2.3]
```

2024-12-17 10:20 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.0]
```

2024-12-17 10:21 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.2)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.2]
```

2024-12-17 10:21 UTC, Remi-Gau commented on nilearn/plotting/displays/_slicers.py
> +    _default_figsize: ClassVar[list[float, float]] = (2.2, 3.0)
```suggestion
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.0]
```

2024-12-17 10:23 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```suggestion
    _cut_displayed: ClassVar[str] = "z"
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```

2024-12-17 10:23 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```suggestion
    _cut_displayed: ClassVar[str] = "yz"
    _default_figsize: ClassVar[list[float, float]] = [2.2, 3.4]
```

2024-12-17 10:23 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = [2.6, 3.0]
```suggestion
    _cut_displayed: ClassVar[str] = "l"
    _default_figsize: ClassVar[list[float, float]] = [2.6, 3.0]
```

2024-12-17 10:23 UTC, Remi-Gau commented on nilearn/plotting/displays/_projectors.py
> +_default_figsize: ClassVar[list[float, float]] = [2.6, 2.8]
```suggestion
    _cut_displayed: ClassVar[str] = "r"
    _default_figsize: ClassVar[list[float, float]] = [2.6, 2.8]
```

2024-12-17 11:20 UTC, Remi-Gau commented on doc/changes/latest.rst
> +- :bdg-dark:`Code` Fix all occurrences of the RUF012 error related to mutable default values in Python classes (:gh:`4954` by `Idrissa Traore_).
```suggestion
- :bdg-dark:`Code` Fix all occurrences of the RUF012 error related to mutable default values in Python classes (:gh:`4954` by `Idrissa Traore`_).
```

2024-12-17 21:18 UTC, bthirion approved these changes
Thx !

2024-12-17 23:06 UTC, merged