[ENH] Add reports for SurfaceMapsMasker
nilearn/nilearn pull request #4968
Opened 2024-12-18 14:49 UTC by man-shu

- Closes None but relates to #4830 

Changes proposed in this pull request:

-
-

2024-12-20 14:24 UTC, man-shu commented
Preview of what the report looks like on 1080x1920 res
![Screenshot 2024-12-20 at 3 21 19 PM](https://github.com/user-attachments/assets/c213189e-5f47-45a4-ad9a-e5196648e549)
You need to scroll down to see the other side of the hemispheres, even though there is space at the bottom. There seems to be a "box" that is smaller than the whole page.

I will either to expand that box or decrease the vertical space between the subplots

2024-12-23 15:00 UTC, man-shu commented
Any specific reason why we don't use plotly for the plots in reports? I tried it and it looks better IMO:
![Screenshot 2024-12-23 at 3 57 36 PM](https://github.com/user-attachments/assets/9fbad34c-9b48-4cbe-99a0-c42f56c63cf3)

- However would be much better to first resolve #4664

2024-12-23 15:04 UTC, man-shu commented
* And doing this would (partly) resolve #4886

2024-12-23 15:34 UTC, bthirion commented
I have no issue with using plotly in reports.

2024-12-23 17:03 UTC, Remi-Gau commented
> I have no issue with using plotly in reports.

good with me as well though it means report can only be generated when plotly is installed where as for other maskers they only require matplotlib

where you thinking of embedding static figures or interactive HTML iframes?

2024-12-23 17:17 UTC, man-shu commented
> good with me as well though it means report can only be generated when plotly is installed where as for other maskers they only require matplotlib

How I've implemented it right now, it would fall back to matplotlib if no plotly.

> where you thinking of embedding static figures or interactive HTML iframes?

It's interactive, see: https://drive.google.com/file/d/1QLEFEKnMhYjPR2YbXKMQvSLMVQm1LfZS/view?usp=sharing

I guess one downside might be that the report would be huge -- this one is 14 MB. It's because we are embedding Plotly's CSS into the HTML as of now. They have an option where we can just provide Plotly's CDN link, and it would fetch the CSS from there every time you open it. But that would mean the report won't show the figure when you're offline...

2024-12-23 17:31 UTC, Remi-Gau commented
> I guess one downside might be that the report would be huge

that was my other concern: I'd prefer to have smaller report by default

2024-12-24 13:18 UTC, man-shu commented
Ok, now I am using `view_surf` instead of `plot_surf` to get the plotly figure's HTML, and that seems to be lighter.

So, if we plot using the following example, these are the options we have:
1. Matplotlib's SVG: static, **57MB**, [report_mpl_svg.html](https://drive.google.com/file/d/17VEOpJYB4hK0xvg6whK3HLRnZhsmmltW/view?usp=sharing) : Right now, we are using this in SurfaceMasker and SurfaceLabelsMasker. On this PR, with SurfaceMapsMasker, this would be used if no plotly.
2. Plotly: interactive, 9.1 MB, [report_plotly.html](https://drive.google.com/file/d/11HHIuO6Xb36CiF9WrHrk_BcyzkGGAz1r/view?usp=sharing) : Proposed default on this PR.
3. Matplotlib's PNG: static, 1.7MB, [report_mpl_png.html](https://drive.google.com/file/d/1XD-YzDZVsuqX_y1lw5xkVd-isOwQUv8s/view?usp=sharing): Does not work on Chrome browsers as of now, but easily fixable.


Code to generate above reports:
```python
# %%
from nilearn.datasets import (
    fetch_atlas_difumo,
    fetch_atlas_msdl,
    load_nki,
    load_fsaverage,
)
from nilearn.maskers import SurfaceMapsMasker
from nilearn.surface import SurfaceImage
from nilearn.maskers._utils import (
    compute_mean_surface_image,
)
from nilearn.plotting import plot_surf, show, view_surf
import numpy as np
from pathlib import Path

# Fetch the a volumetric probabilistic atlas
atlas = fetch_atlas_msdl()
# or
# atlas = fetch_atlas_difumo()
# Fetch the fsaverage5 mesh
fsaverage5_mesh = load_fsaverage("fsaverage5")["pial"]
# Fetch the NKI dataset
surf_img = load_nki()[0]
mean_surf_img = compute_mean_surface_image(surf_img)
# project atlas to the surface
surf_atlas = SurfaceImage.from_volume(
    volume_img=atlas.maps, mesh=fsaverage5_mesh
)
# Create a masker object
masker = SurfaceMapsMasker(surf_atlas).fit()
# Extract the time series
time_series = masker.transform(surf_img)
# see masker report
report = masker.generate_report(3)
report.save_as_html(Path("report.html"))
```

2024-12-26 11:16 UTC, bthirion commented
So, we use plotly if available, otherwise matplotlib if available. Sounds reasonable to me.

2024-12-30 12:58 UTC, man-shu commented
So the current failure seems to happen because we require matplotlib to be installed in order to use reporting, via:
https://github.com/nilearn/nilearn/blob/655bb5fb4b224b44c4c6013f57e5c2a074fdf38e/nilearn/reporting/__init__.py#L10

The way I see it, we would prefer Matplotlib for Nifti maskers and Plotly for Surface maskers (only surface maps masker in this PR, but this behavior could be replicated for the others). 

So I suppose instead of requiring only matplotlib at the init of reporting module, it would be better to set the preference at individual masker-level? I will open a separate PR for this.

But LMWYT @Remi-Gau @bthirion

2025-01-02 07:40 UTC, bthirion commented
Not sure I follow you: For sufaceMasker, we prefer plotly, but using mpl remains OK ? So what is wrong about requiring only mpl at the module level ?
(my thought is: try to keep it simple...)

2025-01-13 13:24 UTC, man-shu commented
> Not sure I follow you: For sufaceMasker, we prefer plotly, but using mpl remains OK ? So what is wrong about requiring only mpl at the module level ? (my thought is: try to keep it simple...)

I wanted to make plotly the 1st priority for surface maskers. This means surface masker reports should work as long as plotly is there (even if matplotlib is not). But as we have it right now, we can't even import the reporting module unless matplotlib is installed.

2025-01-13 13:48 UTC, Remi-Gau commented
> This means surface masker reports should work as long as plotly is there (even if matplotlib is not).

I am pretty sure that matplotlib is dependency of plotly, so if you have plotly, then matplotlib will be there.

2025-01-13 13:49 UTC, Remi-Gau commented
> So, we use plotly if available, otherwise matplotlib if available. Sounds reasonable to me.

I would actually stick to matplotlib being the default and only have plotly as optional given the size of of the generated report.

2025-01-13 14:17 UTC, man-shu commented
> given the size of of the generated report.

I actually found that the report would be heavier if we insert a matplotlib figure as SVG in the report. See https://github.com/nilearn/nilearn/pull/4968#issuecomment-2561122727

> I am pretty sure that matplotlib is dependency of plotly, so if you have plotly, then matplotlib will be there.

OK then let's just stick to matplotlib as 1st priority

2025-01-14 12:20 UTC, man-shu commented on nilearn/reporting/utils.py
> +    return base64.b64encode(figure_to_png_bytes(fig)).decode()
This function was removed in #5038. Seems like we never used it before, but we need it to create png images in the reports.

2025-01-14 12:44 UTC, man-shu commented
* Ok looks like now all the fails are related to #5044

2025-01-14 22:09 UTC, bthirion reviewed
Almost there. Where can I see an example of generated report ?

2025-01-15 13:02 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            return [None]
`test_reports_false` was supposed to cover this but somehow it isn't. Let me have another look

2025-01-15 13:09 UTC, man-shu commented
The plotly engine doesn't work anymore (issue with `view_surf`). But it was when I started working on this -- all the screenshots and HTMLs above are the proof. Something seems to have changed since then (between 0.11.0 and 0.11.1) it could either be on our end or maybe plotly

* This is related to #5018 specifically [this comment](https://github.com/nilearn/nilearn/issues/5018#issuecomment-2592402254)

2025-01-15 14:12 UTC, man-shu commented on nilearn/plotting/html_surface.py
> +    info["vertexcolor_both"] = get_vertexcolor(
> The plotly engine doesn't work anymore (issue with `view_surf`).

This fixes `view_surf`. Seems like I introduced it in #4991. But that shouldn't have affected the stable docs. Weird...

2025-01-15 14:29 UTC, man-shu commented
> Almost there. Where can I see an example of generated report ?

Ran a full doc build let's wait

2025-01-16 09:15 UTC, man-shu commented
The docs are here: https://github.com/nilearn/nilearn/actions/runs/12793251992/artifacts/2436872603

Seems like there are a couple of issues:
1. The plotly figure is a bit too big when displayed on a smaller screen; maybe I can make the size of the figure responsive.
2. The buttons to see the next maps don't work properly. Not just for surface maps masker but all the maps masker (nifti and multi nifti).

On a positive note, the issue with `view_surf` has been fixed (related to https://github.com/nilearn/nilearn/issues/5018#issuecomment-2592402254), even on the `plot_surface_101.py` example (see the screenshot below). This means the bug was indeed introduced in #4991. However, this PR has not been released yet, so the issues on stable docs don't make any sense to me.

<img width="1103" alt="Screenshot 2025-01-16 at 10 10 02 AM" src="https://github.com/user-attachments/assets/7575783d-750b-46cc-84d5-d92ea884bea5" />

2025-01-16 15:35 UTC, man-shu commented
Updated doc build: https://github.com/nilearn/nilearn/actions/runs/12808487443/artifacts/2441538351.

The plotly figure can't be any more responsive than it is now. And we will deal with the other two issues in separate PRs.
So good to review now @bthirion @Remi-Gau

2025-01-17 15:56 UTC, Remi-Gau commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
I think it may be useful to maybe use the `pyplot` fixure

https://github.com/nilearn/nilearn/blob/bc67775f6153c533e18edaabdb551b7f4c1f5e4e/nilearn/plotting/tests/conftest.py#L7

Like used here for example: 

https://github.com/nilearn/nilearn/blob/bc67775f6153c533e18edaabdb551b7f4c1f5e4e/nilearn/plotting/tests/test_surf_plotting.py#L275

it will just skip the test if matplotlib is not there

feel free to move the content from `nilearn/plotting/tests/conftest.py` to `nilearn/conftest.py`

2025-01-17 16:19 UTC, Remi-Gau commented on nilearn/reporting/data/html/report_body_template_surfacemapsmasker.html
> +    </div>
realise that the glm report code has a way to easily turn pandas dataframe into html code: let's refactor after this PR is in

2025-01-17 19:49 UTC, emdupre commented on nilearn/reporting/data/html/report_body_template_surfacemapsmasker.html
> +  }
+1 to extract and also to document in a follow-up PR ; most nilearn devs don't have JS expertise so longterm maintenance gets tricker for these snippets unless they're clearly marked and have some description !

2025-01-20 09:00 UTC, man-shu commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
Nice! Is it ok if I rename `pyplot` fixture to `matplotlib`?
I got confused for a second between `plotly` and `pyplot`.

2025-01-20 09:38 UTC, Remi-Gau commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
> Is it ok if I rename `pyplot` fixture to `matplotlib`?

yup fine: though makes me realize that having a fixture with the same name as a package or a module sounds like recipe for disaster if we end up doing `import matplolib` and no alias it via `import matplotlib as mpl`

2025-01-20 09:41 UTC, man-shu commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
Yeah fair point. How about matplotlib_pyplot?

2025-01-20 10:11 UTC, man-shu commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
Also @Remi-Gau how did you get around ARG001 Ruff failures in [`nilearn/nilearn/plotting/tests/test_surf_plotting.py`](https://github.com/nilearn/nilearn/blob/bc67775f6153c533e18edaabdb551b7f4c1f5e4e/nilearn/plotting/tests/test_surf_plotting.py#L275)

![Screenshot 2025-01-20 at 11 10 21 AM](https://github.com/user-attachments/assets/81f3b80d-2f11-4906-a13f-822042d6c665)

2025-01-20 12:57 UTC, Remi-Gau commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
used the very unsubtle nuclear option:

https://github.com/nilearn/nilearn/blob/b851ecc5a14a6d11aa9f8c2aa59cbede493e699f/nilearn/plotting/tests/test_surf_plotting.py#L3

2025-01-20 15:17 UTC, man-shu commented on nilearn/maskers/tests/test_surface_maps_masker.py
> +)
Done: https://github.com/nilearn/nilearn/pull/4968/commits/fe94ca58b1223effbf54a4c625eff3b5300fa760

2025-01-21 22:02 UTC, bthirion reviewed
Almost done. Just one minor comment.

2025-01-21 22:02 UTC, bthirion commented on nilearn/maskers/surface_maps_masker.py
> +            # TODO: possibly allow to generate a report with other views
do you plan to do this in a future PR ?

2025-01-22 10:40 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            # TODO: possibly allow to generate a report with other views
I think it got copied from another masker. But let's open an issue to track it.

2025-01-22 12:01 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            warnings.warn(
Ok no sorry it's actually the opposite -- we run this test when we only have matplotlib and no plotly. We do have the `no_plotly` test env for that. And this test actually passes there: https://github.com/nilearn/nilearn/actions/runs/12871770600/job/35888836502#step:7:7061

So I am not sure why does codecov complain...

2025-01-22 12:41 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            # TODO: possibly allow to generate a report with other views
* see #5081

2025-01-22 15:09 UTC, Remi-Gau requested changes
changelog needs an update

2025-01-22 15:34 UTC, man-shu commented
Done!

2025-01-22 19:10 UTC, man-shu commented
Reports are at the bottom of this page: https://output.circle-artifacts.com/output/job/e70086e5-20f0-47e2-848b-0ac4fa5452bf/artifacts/0/dev/modules/generated_reports/masker_reports_examples.html#surface-maskers

2025-01-22 21:27 UTC, bthirion approved these changes
LGTM, thx.

2025-01-23 10:14 UTC, Remi-Gau commented on nilearn/maskers/surface_maps_masker.py
> +            ).get_iframe()
pass the cmap here:

the report show a divergent colormap and we most likely will be plotting probabilities that work better with a sequential map like inferno

![image](https://github.com/user-attachments/assets/87c4149e-5bb0-4850-92fd-1cd8fae5dc96)

2025-01-23 10:15 UTC, Remi-Gau commented on nilearn/maskers/surface_maps_masker.py
> +            ).get_iframe()
also the iframe should probably not be so wide: that's a CSS issue we can maybe fix in a follow up PR

2025-01-23 15:09 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            ).get_iframe()
> also the iframe should probably not be so wide: that's a CSS issue we can maybe fix in a follow up PR

Ok, for now, I hard-coded a smaller width, but I think Plotly allows the plots to be responsive to window size. Let's do that in a later PR.

2025-01-24 09:01 UTC, man-shu commented on nilearn/maskers/surface_maps_masker.py
> +            ).get_iframe()
Better now

<img width="820" alt="Screenshot 2025-01-24 at 10 00 49 AM" src="https://github.com/user-attachments/assets/eace3dab-0f6d-474c-8f58-af6dd4ddc394" />

2025-01-24 15:26 UTC, Remi-Gau approved these changes

2025-01-24 15:26 UTC, merged